# see http://jekyllrb.com/docs/configuration/

# Dependencies
markdown:           kramdown
highlighter:        rouge

# Permalinks
permalink:          /blog/:title

# Setup
title:              Kent Boogaart
tagline:            My Sliding Window
url:                http://kent-boogaart.com
paginate:           1
baseurl:            /
exclude:            [ Gemfile, icon.svg, CreatePost.ps1 ]
author:
  name:             Kent Boogaart
  url:              http://kent-boogaart.com
  email:            kent.boogaart@gmail.com

# Feed vars
name:               Kent Boogaart
description:        Kent Boogaart's Blog

# Custom vars
version:            1.0.0
github:
  repo:             https://github.com/kentcb/kentcb.github.io

defaults:
  -
    scope:
      path:         ""          # all files
      type:         posts       # only posts though
    values:
      layout:       post
  -
    scope:
      path:         ""          # all files
      type:         pages       # only pages though
    values:
      layout:       page